name: ai_notes_flutter
description: AI-powered note-taking app with multi-format support and intelligent features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  
  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Database & Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # File Handling
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  
  # Audio & Video
  just_audio: ^0.9.35
  video_player: ^2.7.2
  record: ^5.0.0
  audioplayers: ^5.2.1
  
  # PDF & Document
  syncfusion_flutter_pdfviewer: ^23.1.38
  flutter_pdfview: ^1.3.2
  
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  
  # WebView for CRDT Editor
  flutter_inappwebview: ^6.0.0
  webview_flutter: ^4.4.1
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.8
  shimmer: ^3.0.0
  
  # Text Processing
  markdown: ^7.1.1
  flutter_markdown: ^0.6.18
  
  # Utils
  uuid: ^4.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  
  # Cloud Services
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  
  # Network
  connectivity_plus: ^5.0.1
  
  # Platform Specific
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Integration Testing
  integration_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/web/
    - assets/images/
    - assets/icons/
    - assets/audio/
