// 示例：如何通过metadata将实体关联
// 
// 这个文件展示了如何使用metadata字段在不同实体之间建立关联关系

import '../features/notes/domain/entities/note.dart';
import '../features/flashcards/domain/entities/entities.dart';
import '../features/quiz/domain/entities/entities.dart';

class EntityRelationshipExamples {
  /// 示例1：在Note的metadata中存储关联的FlashcardSet和QuizSet ID
  static Note createNoteWithAssociations() {
    return Note(
      id: 'note_1',
      title: '英语语法学习笔记',
      content: '这是关于英语语法的学习笔记内容...',
      type: NoteType.text,
      status: NoteStatus.published,
      tags: ['English', 'Grammar'],
      attachments: [],
      keywords: ['grammar', 'tense', 'verb'],
      userId: 'user_123',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      metadata: {
        'associatedFlashcardSets': ['flashcard_set_1', 'flashcard_set_2'],
        'associatedQuizSets': ['quiz_set_1'],
        'targetFolder': '/English/Grammar',
        'crdtDocumentId': 'crdt_doc_123',
      },
    );
  }

  /// 示例2：在FlashcardSet的metadata中存储关联的Note ID
  static FlashcardSet createFlashcardSetWithNoteAssociation() {
    return FlashcardSet(
      id: 'flashcard_set_1',
      title: '英语语法卡片集',
      description: '基于英语语法笔记生成的闪卡集合',
      flashcardIds: ['flashcard_1', 'flashcard_2', 'flashcard_3'],
      userId: 'user_123',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      metadata: {
        'sourceNoteId': 'note_1',  // 关联的源笔记ID
        'autoGenerated': true,     // 是否自动生成
        'difficulty': 'medium',    // 整体难度
      },
    );
  }

  /// 示例3：在Flashcard的metadata中存储详细关联信息
  static Flashcard createFlashcardWithAssociations() {
    return Flashcard(
      id: 'flashcard_1',
      setId: 'flashcard_set_1',  // 属于flashcard_set_1
      question: 'What is the past tense of "go"?',
      answer: 'went',
      hint: 'It\'s an irregular verb',
      difficulty: FlashcardDifficulty.easy,
      status: FlashcardStatus.active,
      userId: 'user_123',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      metadata: {
        'sourceNoteId': 'note_1',           // 来源笔记ID
        'noteSection': 'irregular-verbs',    // 笔记中的具体章节
        'autoGenerated': true,               // 是否自动生成
        'confidenceLevel': 0.85,             // AI生成的置信度
      },
    );
  }

  /// 示例4：在QuizSet的metadata中存储关联信息
  static QuizSet createQuizSetWithNoteAssociation() {
    return QuizSet(
      id: 'quiz_set_1',
      title: '英语语法测验',
      description: '基于英语语法笔记的综合测验',
      type: QuizType.mixed,
      status: QuizStatus.active,
      quizIds: ['quiz_1', 'quiz_2', 'quiz_3'],
      timeLimit: 30, // 30分钟
      shuffleQuestions: true,
      showCorrectAnswers: true,
      userId: 'user_123',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      metadata: {
        'sourceNoteIds': ['note_1'],        // 可以关联多个笔记
        'targetAudience': 'intermediate',    // 目标受众
        'passingScore': 70,                  // 及格分数
        'maxAttempts': 3,                    // 最大尝试次数
      },
    );
  }

  /// 示例5：在Quiz的metadata中存储详细信息
  static Quiz createQuizWithAssociations() {
    return Quiz(
      id: 'quiz_1',
      setId: 'quiz_set_1',  // 属于quiz_set_1
      question: 'Which of the following is the correct past tense of "run"?',
      type: QuizQuestionType.multipleChoice,
      options: [
        QuizOption(id: 'opt_1', text: 'runned', isCorrect: false),
        QuizOption(id: 'opt_2', text: 'ran', isCorrect: true),
        QuizOption(id: 'opt_3', text: 'runed', isCorrect: false),
        QuizOption(id: 'opt_4', text: 'running', isCorrect: false),
      ],
      explanation: 'The past tense of "run" is "ran". It\'s an irregular verb.',
      difficulty: QuizDifficulty.easy,
      status: QuizQuestionStatus.active,
      points: 2,
      userId: 'user_123',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      metadata: {
        'sourceNoteId': 'note_1',           // 来源笔记ID
        'noteSection': 'irregular-verbs',    // 笔记中的具体章节
        'relatedFlashcardId': 'flashcard_1', // 相关的闪卡ID
        'bloomTaxonomy': 'knowledge',        // 布鲁姆分类法级别
        'autoGenerated': true,               // 是否自动生成
      },
    );
  }
}

/// 查询关联关系的辅助方法
class RelationshipQueries {
    /// 从Note获取关联的FlashcardSet IDs
    static List<String> getAssociatedFlashcardSets(Note note) {
      final metadata = note.metadata;
      if (metadata == null) return [];
      
      final associated = metadata['associatedFlashcardSets'];
      if (associated is List) {
        return associated.cast<String>();
      }
      return [];
    }

    /// 从Note获取关联的QuizSet IDs
    static List<String> getAssociatedQuizSets(Note note) {
      final metadata = note.metadata;
      if (metadata == null) return [];
      
      final associated = metadata['associatedQuizSets'];
      if (associated is List) {
        return associated.cast<String>();
      }
      return [];
    }

    /// 从FlashcardSet获取源Note ID
    static String? getSourceNoteId(FlashcardSet flashcardSet) {
      return flashcardSet.metadata?['sourceNoteId'] as String?;
    }

    /// 从QuizSet获取源Note IDs
    static List<String> getSourceNoteIds(QuizSet quizSet) {
      final metadata = quizSet.metadata;
      if (metadata == null) return [];
      
      final sourceIds = metadata['sourceNoteIds'];
      if (sourceIds is List) {
        return sourceIds.cast<String>();
      }
      return [];
    }

    /// 检查Flashcard是否是自动生成的
    static bool isAutoGenerated(Flashcard flashcard) {
      return flashcard.metadata?['autoGenerated'] as bool? ?? false;
    }

    /// 检查Quiz是否是自动生成的
    static bool isQuizAutoGenerated(Quiz quiz) {
      return quiz.metadata?['autoGenerated'] as bool? ?? false;
    }
}
